// <auto-generated />
namespace E_Commerce_Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class E_Commerce_Web : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(E_Commerce_Web));
        
        string IMigrationMetadata.Id
        {
            get { return "202209151318020_E_Commerce_Web"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
