// <auto-generated />
namespace E_Commerce_Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Migration_E_commerce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration_E_commerce));
        
        string IMigrationMetadata.Id
        {
            get { return "202209171846240_Migration_E_commerce"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
