namespace E_Commerce_Repository.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class UpdateDB : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Accounts", "AccountState_Id", "dbo.AccountStates");
            DropForeignKey("dbo.Accounts", "Position_Id", "dbo.Positions");
            DropForeignKey("dbo.Promotions", "AccountAdmin_Id", "dbo.Accounts");
            DropForeignKey("dbo.Products", "Promotion_Id", "dbo.Promotions");
            DropForeignKey("dbo.Products", "Company_Id", "dbo.Companies");
            DropForeignKey("dbo.Feedbacks", "Product_Id", "dbo.Products");
            DropForeignKey("dbo.OrderDetails", "Product_Id", "dbo.Products");
            DropForeignKey("dbo.ProductImages", "Product_Id", "dbo.Products");
            DropForeignKey("dbo.ShoppingCardDetails", "Product_Id", "dbo.Products");
            DropForeignKey("dbo.Products", "Supplier_Id", "dbo.Suppliers");
            DropForeignKey("dbo.Products", "TypeProduct_Id", "dbo.TypeProducts");
            DropForeignKey("dbo.WarehouseProducts", "Products_Id", "dbo.Products");
            DropForeignKey("dbo.Feedbacks", "AccountConsumer_Id", "dbo.Accounts");
            DropForeignKey("dbo.Orders", "Address_Id", "dbo.Addresses");
            DropForeignKey("dbo.Orders", "AccountConsumer_Id", "dbo.Accounts");
            DropForeignKey("dbo.Orders", "DeliverState_Id", "dbo.DeliverStates");
            DropForeignKey("dbo.OrderDetails", "Order_Id", "dbo.Orders");
            DropForeignKey("dbo.Orders", "PaymentMethod_Id", "dbo.PaymentMethods");
            DropForeignKey("dbo.Orders", "ShippingMethod_Id", "dbo.ShippingMethods");
            DropForeignKey("dbo.WarehouseProducts", "Warehouses_Id", "dbo.Warehouses");
            DropForeignKey("dbo.ShoppingCardDetails", "ShoppingCard_Id", "dbo.ShoppingCards");
            DropForeignKey("dbo.TypeProducts", "Category_Id", "dbo.Categories");
            DropIndex("dbo.Accounts", new[] { "AccountState_Id" });
            DropIndex("dbo.Promotions", new[] { "AccountAdmin_Id" });
            DropIndex("dbo.Products", new[] { "Company_Id" });
            DropIndex("dbo.Products", new[] { "Promotion_Id" });
            DropIndex("dbo.Products", new[] { "Supplier_Id" });
            DropIndex("dbo.Products", new[] { "TypeProduct_Id" });
            DropIndex("dbo.Feedbacks", new[] { "AccountConsumer_Id" });
            DropIndex("dbo.Feedbacks", new[] { "Product_Id" });
            DropIndex("dbo.Orders", new[] { "AccountConsumer_Id" });
            DropIndex("dbo.Orders", new[] { "Address_Id" });
            DropIndex("dbo.Orders", new[] { "DeliverState_Id" });
            DropIndex("dbo.Orders", new[] { "PaymentMethod_Id" });
            DropIndex("dbo.Orders", new[] { "ShippingMethod_Id" });
            DropIndex("dbo.OrderDetails", new[] { "Order_Id" });
            DropIndex("dbo.OrderDetails", new[] { "Product_Id" });
            DropIndex("dbo.WarehouseProducts", new[] { "Products_Id" });
            DropIndex("dbo.WarehouseProducts", new[] { "Warehouses_Id" });
            DropIndex("dbo.ShoppingCardDetails", new[] { "Product_Id" });
            DropIndex("dbo.ShoppingCardDetails", new[] { "ShoppingCard_Id" });
            DropIndex("dbo.ProductImages", new[] { "Product_Id" });
            DropIndex("dbo.TypeProducts", new[] { "Category_Id" });
            RenameColumn(table: "dbo.Accounts", name: "AccountState_Id", newName: "AccountStateId");
            RenameColumn(table: "dbo.Accounts", name: "Position_Id", newName: "PositionId");
            RenameColumn(table: "dbo.Promotions", name: "AccountAdmin_Id", newName: "AccountAdminID");
            RenameColumn(table: "dbo.Products", name: "Promotion_Id", newName: "PromotionID");
            RenameColumn(table: "dbo.Products", name: "Company_Id", newName: "CompanyID");
            RenameColumn(table: "dbo.Feedbacks", name: "Product_Id", newName: "ProductID");
            RenameColumn(table: "dbo.OrderDetails", name: "Product_Id", newName: "ProductID");
            RenameColumn(table: "dbo.ProductImages", name: "Product_Id", newName: "ProductID");
            RenameColumn(table: "dbo.ShoppingCardDetails", name: "Product_Id", newName: "ProductID");
            RenameColumn(table: "dbo.Products", name: "Supplier_Id", newName: "SupplierID");
            RenameColumn(table: "dbo.Products", name: "TypeProduct_Id", newName: "TypeProductID");
            RenameColumn(table: "dbo.WarehouseProducts", name: "Products_Id", newName: "productId");
            RenameColumn(table: "dbo.Feedbacks", name: "AccountConsumer_Id", newName: "AccountConsumerID");
            RenameColumn(table: "dbo.Orders", name: "Address_Id", newName: "AddressID");
            RenameColumn(table: "dbo.Orders", name: "AccountConsumer_Id", newName: "AccountConsumerID");
            RenameColumn(table: "dbo.Orders", name: "DeliverState_Id", newName: "DeliverStateID");
            RenameColumn(table: "dbo.OrderDetails", name: "Order_Id", newName: "OrderID");
            RenameColumn(table: "dbo.Orders", name: "PaymentMethod_Id", newName: "PaymentMethodId");
            RenameColumn(table: "dbo.Orders", name: "ShippingMethod_Id", newName: "ShippingMethodID");
            RenameColumn(table: "dbo.WarehouseProducts", name: "Warehouses_Id", newName: "WarehousesID");
            RenameColumn(table: "dbo.ShoppingCardDetails", name: "ShoppingCard_Id", newName: "ShoppingCardID");
            RenameColumn(table: "dbo.TypeProducts", name: "Category_Id", newName: "CategoryID");
            RenameIndex(table: "dbo.Accounts", name: "IX_Position_Id", newName: "IX_PositionId");
            AddColumn("dbo.Accounts", "BankingCardsId", c => c.Int());
            AddColumn("dbo.Accounts", "ShoppingCardsId", c => c.Int());
            AddColumn("dbo.Products", "DescribeID", c => c.Int(nullable: false));
            AddColumn("dbo.Describes", "ProductID", c => c.Int(nullable: false));
            AddColumn("dbo.Addresses", "ProvinceID", c => c.Int(nullable: false));
            AddColumn("dbo.Addresses", "DistrictID", c => c.Int(nullable: false));
            AddColumn("dbo.Addresses", "WardsID", c => c.Int(nullable: false));
            AddColumn("dbo.Districts", "AddressID", c => c.Int(nullable: false));
            AddColumn("dbo.Provinces", "AddressID", c => c.Int(nullable: false));
            AddColumn("dbo.Wards", "AddressID", c => c.Int(nullable: false));
            AddColumn("dbo.Warehouses", "AddressesID", c => c.Int(nullable: false));
            AddColumn("dbo.BankingCards", "AccountConsumerID", c => c.Int(nullable: false));
            AddColumn("dbo.ShoppingCards", "AccountConsumerID", c => c.Int(nullable: false));
            AlterColumn("dbo.Accounts", "AccountStateId", c => c.Int(nullable: false));
            AlterColumn("dbo.Promotions", "AccountAdminID", c => c.Int(nullable: false));
            AlterColumn("dbo.Products", "CompanyID", c => c.Int(nullable: false));
            AlterColumn("dbo.Products", "PromotionID", c => c.Int(nullable: false));
            AlterColumn("dbo.Products", "SupplierID", c => c.Int(nullable: false));
            AlterColumn("dbo.Products", "TypeProductID", c => c.Int(nullable: false));
            AlterColumn("dbo.Feedbacks", "AccountConsumerID", c => c.Int(nullable: false));
            AlterColumn("dbo.Feedbacks", "ProductID", c => c.Int(nullable: false));
            AlterColumn("dbo.Orders", "AccountConsumerID", c => c.Int(nullable: false));
            AlterColumn("dbo.Orders", "AddressID", c => c.Int(nullable: false));
            AlterColumn("dbo.Orders", "DeliverStateID", c => c.Int(nullable: false));
            AlterColumn("dbo.Orders", "PaymentMethodId", c => c.Int(nullable: false));
            AlterColumn("dbo.Orders", "ShippingMethodID", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderDetails", "OrderID", c => c.Int(nullable: false));
            AlterColumn("dbo.OrderDetails", "ProductID", c => c.Int(nullable: false));
            AlterColumn("dbo.WarehouseProducts", "productId", c => c.Int(nullable: false));
            AlterColumn("dbo.WarehouseProducts", "WarehousesID", c => c.Int(nullable: false));
            AlterColumn("dbo.ShoppingCardDetails", "ProductID", c => c.Int(nullable: false));
            AlterColumn("dbo.ShoppingCardDetails", "ShoppingCardID", c => c.Int(nullable: false));
            AlterColumn("dbo.ProductImages", "ProductID", c => c.Int(nullable: false));
            AlterColumn("dbo.TypeProducts", "CategoryID", c => c.Int(nullable: true));
            CreateIndex("dbo.Accounts", "AccountStateId");
            CreateIndex("dbo.Promotions", "AccountAdminID");
            CreateIndex("dbo.Products", "TypeProductID");
            CreateIndex("dbo.Products", "SupplierID");
            CreateIndex("dbo.Products", "CompanyID");
            CreateIndex("dbo.Products", "PromotionID");
            CreateIndex("dbo.Feedbacks", "AccountConsumerID");
            CreateIndex("dbo.Feedbacks", "ProductID");
            CreateIndex("dbo.Orders", "ShippingMethodID");
            CreateIndex("dbo.Orders", "PaymentMethodId");
            CreateIndex("dbo.Orders", "AddressID");
            CreateIndex("dbo.Orders", "DeliverStateID");
            CreateIndex("dbo.Orders", "AccountConsumerID");
            CreateIndex("dbo.OrderDetails", "OrderID");
            CreateIndex("dbo.OrderDetails", "ProductID");
            CreateIndex("dbo.WarehouseProducts", "productId");
            CreateIndex("dbo.WarehouseProducts", "WarehousesID");
            CreateIndex("dbo.ShoppingCardDetails", "ShoppingCardID");
            CreateIndex("dbo.ShoppingCardDetails", "ProductID");
            CreateIndex("dbo.ProductImages", "ProductID");
            CreateIndex("dbo.TypeProducts", "CategoryID");
            AddForeignKey("dbo.Accounts", "AccountStateId", "dbo.AccountStates", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Accounts", "PositionId", "dbo.Positions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Promotions", "AccountAdminID", "dbo.Accounts", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "PromotionID", "dbo.Promotions", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "CompanyID", "dbo.Companies", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Feedbacks", "ProductID", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderDetails", "ProductID", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ProductImages", "ProductID", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ShoppingCardDetails", "ProductID", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "SupplierID", "dbo.Suppliers", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Products", "TypeProductID", "dbo.TypeProducts", "Id", cascadeDelete: true);
            AddForeignKey("dbo.WarehouseProducts", "productId", "dbo.Products", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Feedbacks", "AccountConsumerID", "dbo.Accounts", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Orders", "AddressID", "dbo.Addresses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "AccountConsumerID", "dbo.Accounts", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "DeliverStateID", "dbo.DeliverStates", "Id", cascadeDelete: true);
            AddForeignKey("dbo.OrderDetails", "OrderID", "dbo.Orders", "Id", cascadeDelete: false);
            AddForeignKey("dbo.Orders", "PaymentMethodId", "dbo.PaymentMethods", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Orders", "ShippingMethodID", "dbo.ShippingMethods", "Id", cascadeDelete: true);
            AddForeignKey("dbo.WarehouseProducts", "WarehousesID", "dbo.Warehouses", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ShoppingCardDetails", "ShoppingCardID", "dbo.ShoppingCards", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TypeProducts", "CategoryID", "dbo.Categories", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.TypeProducts", "CategoryID", "dbo.Categories");
            DropForeignKey("dbo.ShoppingCardDetails", "ShoppingCardID", "dbo.ShoppingCards");
            DropForeignKey("dbo.WarehouseProducts", "WarehousesID", "dbo.Warehouses");
            DropForeignKey("dbo.Orders", "ShippingMethodID", "dbo.ShippingMethods");
            DropForeignKey("dbo.Orders", "PaymentMethodId", "dbo.PaymentMethods");
            DropForeignKey("dbo.OrderDetails", "OrderID", "dbo.Orders");
            DropForeignKey("dbo.Orders", "DeliverStateID", "dbo.DeliverStates");
            DropForeignKey("dbo.Orders", "AccountConsumerID", "dbo.Accounts");
            DropForeignKey("dbo.Orders", "AddressID", "dbo.Addresses");
            DropForeignKey("dbo.Feedbacks", "AccountConsumerID", "dbo.Accounts");
            DropForeignKey("dbo.WarehouseProducts", "productId", "dbo.Products");
            DropForeignKey("dbo.Products", "TypeProductID", "dbo.TypeProducts");
            DropForeignKey("dbo.Products", "SupplierID", "dbo.Suppliers");
            DropForeignKey("dbo.ShoppingCardDetails", "ProductID", "dbo.Products");
            DropForeignKey("dbo.ProductImages", "ProductID", "dbo.Products");
            DropForeignKey("dbo.OrderDetails", "ProductID", "dbo.Products");
            DropForeignKey("dbo.Feedbacks", "ProductID", "dbo.Products");
            DropForeignKey("dbo.Products", "CompanyID", "dbo.Companies");
            DropForeignKey("dbo.Products", "PromotionID", "dbo.Promotions");
            DropForeignKey("dbo.Promotions", "AccountAdminID", "dbo.Accounts");
            DropForeignKey("dbo.Accounts", "PositionId", "dbo.Positions");
            DropForeignKey("dbo.Accounts", "AccountStateId", "dbo.AccountStates");
            DropIndex("dbo.TypeProducts", new[] { "CategoryID" });
            DropIndex("dbo.ProductImages", new[] { "ProductID" });
            DropIndex("dbo.ShoppingCardDetails", new[] { "ProductID" });
            DropIndex("dbo.ShoppingCardDetails", new[] { "ShoppingCardID" });
            DropIndex("dbo.WarehouseProducts", new[] { "WarehousesID" });
            DropIndex("dbo.WarehouseProducts", new[] { "productId" });
            DropIndex("dbo.OrderDetails", new[] { "ProductID" });
            DropIndex("dbo.OrderDetails", new[] { "OrderID" });
            DropIndex("dbo.Orders", new[] { "AccountConsumerID" });
            DropIndex("dbo.Orders", new[] { "DeliverStateID" });
            DropIndex("dbo.Orders", new[] { "AddressID" });
            DropIndex("dbo.Orders", new[] { "PaymentMethodId" });
            DropIndex("dbo.Orders", new[] { "ShippingMethodID" });
            DropIndex("dbo.Feedbacks", new[] { "ProductID" });
            DropIndex("dbo.Feedbacks", new[] { "AccountConsumerID" });
            DropIndex("dbo.Products", new[] { "PromotionID" });
            DropIndex("dbo.Products", new[] { "CompanyID" });
            DropIndex("dbo.Products", new[] { "SupplierID" });
            DropIndex("dbo.Products", new[] { "TypeProductID" });
            DropIndex("dbo.Promotions", new[] { "AccountAdminID" });
            DropIndex("dbo.Accounts", new[] { "AccountStateId" });
            AlterColumn("dbo.TypeProducts", "CategoryID", c => c.Int());
            AlterColumn("dbo.ProductImages", "ProductID", c => c.Int());
            AlterColumn("dbo.ShoppingCardDetails", "ShoppingCardID", c => c.Int());
            AlterColumn("dbo.ShoppingCardDetails", "ProductID", c => c.Int());
            AlterColumn("dbo.WarehouseProducts", "WarehousesID", c => c.Int());
            AlterColumn("dbo.WarehouseProducts", "productId", c => c.Int());
            AlterColumn("dbo.OrderDetails", "ProductID", c => c.Int());
            AlterColumn("dbo.OrderDetails", "OrderID", c => c.Int());
            AlterColumn("dbo.Orders", "ShippingMethodID", c => c.Int());
            AlterColumn("dbo.Orders", "PaymentMethodId", c => c.Int());
            AlterColumn("dbo.Orders", "DeliverStateID", c => c.Int());
            AlterColumn("dbo.Orders", "AddressID", c => c.Int());
            AlterColumn("dbo.Orders", "AccountConsumerID", c => c.Int());
            AlterColumn("dbo.Feedbacks", "ProductID", c => c.Int());
            AlterColumn("dbo.Feedbacks", "AccountConsumerID", c => c.Int());
            AlterColumn("dbo.Products", "TypeProductID", c => c.Int());
            AlterColumn("dbo.Products", "SupplierID", c => c.Int());
            AlterColumn("dbo.Products", "PromotionID", c => c.Int());
            AlterColumn("dbo.Products", "CompanyID", c => c.Int());
            AlterColumn("dbo.Promotions", "AccountAdminID", c => c.Int());
            AlterColumn("dbo.Accounts", "AccountStateId", c => c.Int());
            DropColumn("dbo.ShoppingCards", "AccountConsumerID");
            DropColumn("dbo.BankingCards", "AccountConsumerID");
            DropColumn("dbo.Warehouses", "AddressesID");
            DropColumn("dbo.Wards", "AddressID");
            DropColumn("dbo.Provinces", "AddressID");
            DropColumn("dbo.Districts", "AddressID");
            DropColumn("dbo.Addresses", "WardsID");
            DropColumn("dbo.Addresses", "DistrictID");
            DropColumn("dbo.Addresses", "ProvinceID");
            DropColumn("dbo.Describes", "ProductID");
            DropColumn("dbo.Products", "DescribeID");
            DropColumn("dbo.Accounts", "ShoppingCardsId");
            DropColumn("dbo.Accounts", "BankingCardsId");
            RenameIndex(table: "dbo.Accounts", name: "IX_PositionId", newName: "IX_Position_Id");
            RenameColumn(table: "dbo.TypeProducts", name: "CategoryID", newName: "Category_Id");
            RenameColumn(table: "dbo.ShoppingCardDetails", name: "ShoppingCardID", newName: "ShoppingCard_Id");
            RenameColumn(table: "dbo.WarehouseProducts", name: "WarehousesID", newName: "Warehouses_Id");
            RenameColumn(table: "dbo.Orders", name: "ShippingMethodID", newName: "ShippingMethod_Id");
            RenameColumn(table: "dbo.Orders", name: "PaymentMethodId", newName: "PaymentMethod_Id");
            RenameColumn(table: "dbo.OrderDetails", name: "OrderID", newName: "Order_Id");
            RenameColumn(table: "dbo.Orders", name: "DeliverStateID", newName: "DeliverState_Id");
            RenameColumn(table: "dbo.Orders", name: "AccountConsumerID", newName: "AccountConsumer_Id");
            RenameColumn(table: "dbo.Orders", name: "AddressID", newName: "Address_Id");
            RenameColumn(table: "dbo.Feedbacks", name: "AccountConsumerID", newName: "AccountConsumer_Id");
            RenameColumn(table: "dbo.WarehouseProducts", name: "productId", newName: "Products_Id");
            RenameColumn(table: "dbo.Products", name: "TypeProductID", newName: "TypeProduct_Id");
            RenameColumn(table: "dbo.Products", name: "SupplierID", newName: "Supplier_Id");
            RenameColumn(table: "dbo.ShoppingCardDetails", name: "ProductID", newName: "Product_Id");
            RenameColumn(table: "dbo.ProductImages", name: "ProductID", newName: "Product_Id");
            RenameColumn(table: "dbo.OrderDetails", name: "ProductID", newName: "Product_Id");
            RenameColumn(table: "dbo.Feedbacks", name: "ProductID", newName: "Product_Id");
            RenameColumn(table: "dbo.Products", name: "CompanyID", newName: "Company_Id");
            RenameColumn(table: "dbo.Products", name: "PromotionID", newName: "Promotion_Id");
            RenameColumn(table: "dbo.Promotions", name: "AccountAdminID", newName: "AccountAdmin_Id");
            RenameColumn(table: "dbo.Accounts", name: "PositionId", newName: "Position_Id");
            RenameColumn(table: "dbo.Accounts", name: "AccountStateId", newName: "AccountState_Id");
            CreateIndex("dbo.TypeProducts", "Category_Id");
            CreateIndex("dbo.ProductImages", "Product_Id");
            CreateIndex("dbo.ShoppingCardDetails", "ShoppingCard_Id");
            CreateIndex("dbo.ShoppingCardDetails", "Product_Id");
            CreateIndex("dbo.WarehouseProducts", "Warehouses_Id");
            CreateIndex("dbo.WarehouseProducts", "Products_Id");
            CreateIndex("dbo.OrderDetails", "Product_Id");
            CreateIndex("dbo.OrderDetails", "Order_Id");
            CreateIndex("dbo.Orders", "ShippingMethod_Id");
            CreateIndex("dbo.Orders", "PaymentMethod_Id");
            CreateIndex("dbo.Orders", "DeliverState_Id");
            CreateIndex("dbo.Orders", "Address_Id");
            CreateIndex("dbo.Orders", "AccountConsumer_Id");
            CreateIndex("dbo.Feedbacks", "Product_Id");
            CreateIndex("dbo.Feedbacks", "AccountConsumer_Id");
            CreateIndex("dbo.Products", "TypeProduct_Id");
            CreateIndex("dbo.Products", "Supplier_Id");
            CreateIndex("dbo.Products", "Promotion_Id");
            CreateIndex("dbo.Products", "Company_Id");
            CreateIndex("dbo.Promotions", "AccountAdmin_Id");
            CreateIndex("dbo.Accounts", "AccountState_Id");
            AddForeignKey("dbo.TypeProducts", "Category_Id", "dbo.Categories", "Id");
            AddForeignKey("dbo.ShoppingCardDetails", "ShoppingCard_Id", "dbo.ShoppingCards", "Id");
            AddForeignKey("dbo.WarehouseProducts", "Warehouses_Id", "dbo.Warehouses", "Id");
            AddForeignKey("dbo.Orders", "ShippingMethod_Id", "dbo.ShippingMethods", "Id");
            AddForeignKey("dbo.Orders", "PaymentMethod_Id", "dbo.PaymentMethods", "Id");
            AddForeignKey("dbo.OrderDetails", "Order_Id", "dbo.Orders", "Id");
            AddForeignKey("dbo.Orders", "DeliverState_Id", "dbo.DeliverStates", "Id");
            AddForeignKey("dbo.Orders", "AccountConsumer_Id", "dbo.Accounts", "Id");
            AddForeignKey("dbo.Orders", "Address_Id", "dbo.Addresses", "Id");
            AddForeignKey("dbo.Feedbacks", "AccountConsumer_Id", "dbo.Accounts", "Id");
            AddForeignKey("dbo.WarehouseProducts", "Products_Id", "dbo.Products", "Id");
            AddForeignKey("dbo.Products", "TypeProduct_Id", "dbo.TypeProducts", "Id");
            AddForeignKey("dbo.Products", "Supplier_Id", "dbo.Suppliers", "Id");
            AddForeignKey("dbo.ShoppingCardDetails", "Product_Id", "dbo.Products", "Id");
            AddForeignKey("dbo.ProductImages", "Product_Id", "dbo.Products", "Id");
            AddForeignKey("dbo.OrderDetails", "Product_Id", "dbo.Products", "Id");
            AddForeignKey("dbo.Feedbacks", "Product_Id", "dbo.Products", "Id");
            AddForeignKey("dbo.Products", "Company_Id", "dbo.Companies", "Id");
            AddForeignKey("dbo.Products", "Promotion_Id", "dbo.Promotions", "Id");
            AddForeignKey("dbo.Promotions", "AccountAdmin_Id", "dbo.Accounts", "Id");
            AddForeignKey("dbo.Accounts", "Position_Id", "dbo.Positions", "Id");
            AddForeignKey("dbo.Accounts", "AccountState_Id", "dbo.AccountStates", "Id");
        }
    }
}
