// <auto-generated />
namespace E_Commerce_Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IngonreChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IngonreChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202210201247487_IngonreChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
