//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Category
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Newsld { get; set; }
        public Nullable<System.Guid> Categoryld { get; set; }
    }
}
