//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Commerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Voting
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<int> Star { get; set; }
        public string Content { get; set; }
        public Nullable<int> Helpful { get; set; }
        public Nullable<int> Unhelpful { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> Productld { get; set; }
    }
}
